

try{
   //code test
  alert("hi everyone") ;
  alert(x);
 
}
catch(err){
     // handle error
     alert("inside catch block");
     console.log(err);
}
finally{
    alert("bye everyone"); 
}